spring:
  datasource:
    url: jdbc:mysql://localhost:3306/know
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect